import { useState, useEffect } from 'react';
import { Button } from './Button';
import { Modal } from './Modal';
import type { Transaction } from '@types';

interface TransactionFormProps {
  isOpen: boolean;
  onClose: () => void;
  initialData?: Transaction;
}

export const TransactionForm = ({
  isOpen,
  onClose,
  initialData,
}: TransactionFormProps) => {
  const [formData, setFormData] = useState({
    id: '',
    datasetId: '',
    participantId: '',
    action: '',
    amount: '',
    timestamp: '',
  });

  useEffect(() => {
    if (initialData) {
      setFormData({
        id: initialData.id || '',
        datasetId: initialData.datasetId || '',
        participantId: initialData.participantId || '',
        action: initialData.action || '',
        amount: initialData.amount?.toString() || '',
        timestamp: initialData.timestamp || '',
      });
    }
  }, [initialData, isOpen]);

  const footer = (
    <div className="flex gap-3">
      <Button onClick={onClose} variant="primary">
        Close
      </Button>
    </div>
  );

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Transaction Details (Read-Only)"
      size="lg"
      footer={footer}
    >
      <div className="space-y-4">
        <div className="bg-blue-50 border border-blue-200 rounded-md p-3 text-sm text-blue-800">
          Transactions are automatically generated by the system and cannot be manually created or edited.
        </div>

        {/* Transaction ID Field */}
        <div>
          <label className="block text-sm font-medium text-neutral-700 mb-1">
            Transaction ID
          </label>
          <input
            type="text"
            value={formData.id}
            disabled
            className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
          />
        </div>

        {/* Dataset ID Field */}
        <div>
          <label className="block text-sm font-medium text-neutral-700 mb-1">
            Dataset ID
          </label>
          <input
            type="text"
            value={formData.datasetId}
            disabled
            className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
          />
        </div>

        {/* Participant ID Field */}
        <div>
          <label className="block text-sm font-medium text-neutral-700 mb-1">
            Participant ID
          </label>
          <input
            type="text"
            value={formData.participantId}
            disabled
            className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          {/* Action Field */}
          <div>
            <label className="block text-sm font-medium text-neutral-700 mb-1">
              Action
            </label>
            <input
              type="text"
              value={formData.action}
              disabled
              className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
            />
          </div>

          {/* Amount Field */}
          <div>
            <label className="block text-sm font-medium text-neutral-700 mb-1">
              Amount
            </label>
            <input
              type="text"
              value={`${formData.amount} units`}
              disabled
              className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
            />
          </div>
        </div>

        {/* Timestamp Field */}
        <div>
          <label className="block text-sm font-medium text-neutral-700 mb-1">
            Timestamp
          </label>
          <input
            type="text"
            value={formData.timestamp ? new Date(formData.timestamp).toLocaleString() : ''}
            disabled
            className="w-full px-3 py-2 border border-neutral-300 rounded-md text-sm bg-neutral-50 text-neutral-600"
          />
        </div>
      </div>
    </Modal>
  );
};
